#!/usr/bin/env bash
# This script shows numbers 1..20 using a while loop and a case statement
# to add special "bad luck" messages for 4, 9, and 17.

i=1
while [ "$i" -le 20 ]; do
  echo "$i"
  case "$i" in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
    *)
      # nothing else
      ;;
  esac
  i=$((i + 1))
done

