#!/usr/bin/env bash
# This script prints numbers from 1 to 20 with special cases

i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "$i"
    fi
    i=$((i + 1))
done

