#!/usr/bin/env bash
# Check if file exists and its type

if [ ! -e "$1" ]; then
    echo "$1 does not exist"
elif [ -f "$1" ]; then
    echo "$1 is a regular file"
elif [ -d "$1" ]; then
    echo "$1 is a directory"
fi

